# -*- coding: utf-8 -*-
"""Python_Word_Counter_ComputeIDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pQReE6glFM3nq_N4qT-nT7MHpBPF4Rn
"""

with open('demofile.txt') as documentA:
    bagOfWordsA=[word for line in documentA for word in line.split()]

with open('demofile2.txt') as documentB:
    bagOfWordsB=[word for line in documentB for word in line.split()]



uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB))

numOfWordsA = dict.fromkeys(uniqueWords,0)

for word in bagOfWordsA:
    numOfWordsA[word] +=1

numOfWordsB = dict.fromkeys(uniqueWords,0)

for word in bagOfWordsB:
    numOfWordsB[word] +=1


def computeIDF(documents):
    import math
    N = len(documents)

    idfDict = dict.fromkeys(documents[0].keys(), 0)

    for document in documents:
        for word, val in document.items():
            if val >0:
                idfDict[word] += 1

    for word, val in idfDict.items():
        idfDict[word] = math.log(N/float(val))

    return idfDict


idfs = computeIDF([numOfWordsA, numOfWordsB])
print('idfs:',idfs)